apiVersion: v1                  
kind: Service                  
metadata:
  name: developer-service-mariadb  
  labels:                      
    app: developer-service
spec:
  ports:
    - port: 3306
  selector:                     
    app: developer-service
    tier: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: developer-service-mariadb-deployment       
  labels:                         
    app: developer-service
spec:
  selector:
    matchLabels:                 
      app: developer-service
      tier: mariadb
  strategy:
    type: Recreate
  template:                       
    metadata:
      labels:                     
        app: developer-service
        tier: mariadb
    spec:                           
      containers:
      - image: mariadb                
        name: mariadb
        env:                     
        - name: MARIADB_ROOT_PASSWORD 
          value: "abc123"        
        ports:
        - containerPort: 3306       
          name: mariadb
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
---
apiVersion: apps/v1
kind: Deployment            
metadata:
  name: developer-service-server-deployment  
  labels:                  
    app: developer-service-server
spec:
  replicas: 1                 
  selector:
    matchLabels:            
      app: developer-service-server
  template:                   
    metadata:
      labels:                
        app: developer-service-server
    spec:                     
      containers:
      - name: developer-service-server
        image: yentl718/developer-team15
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8051 
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                    
        - name: MARIADB_DB_USERNAME
          value: "root"
        - name: MARIADB_DB_PASSWORD
          value: "abc123"
        - name: MARIADB_DB_HOST
          value: "developer-service-mariadb"
---
apiVersion: v1                     
kind: Service                       
metadata:                     
  name: developer-service-server   
  labels:                          
    app: developer-service-server
spec:                         
  type: NodePort                    
  selector:
    app: developer-service-server  
  ports:                            
  - name: http
    port: 8051
    targetPort: 8051
