apiVersion: v1
kind: Service
metadata:
  name: game-info-service-mongo
  labels:
    app: game-info-service
spec:
  ports:
    - port: 27017
  selector:
    app: game-info-service
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-info-service-mongo-deployment
  labels:        
    app: game-info-service
spec:
  selector:
    matchLabels:   
      app: game-info-service
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: game-info-service
        tier: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-info-service-server-deployment
  labels:
    app: game-info-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-info-service-server
  template:
    metadata:
      labels:
        app: game-info-service-server
    spec:
      containers:
      - name: game-info-service-server
        image: yentl718/game-info-team15
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8052
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: MONGODB_HOST
          value: "game-info-service-mongo"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: game-info-service-server
  labels:
    app: game-info-service-server
spec:
  type: NodePort
  selector:
    app: game-info-service-server
  ports:
  - name: http
    port: 8052
    targetPort: 8052
