apiVersion: apps/v1
kind: Deployment
metadata:
  name: brankedge-service-server-deployment
  labels:
    app: brankedge-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brankedge-service-server
  template:
    metadata:
      labels: 
        app: brankedge-service-server
    spec:
      containers:
        - name: edge-service-server
          image: yentl718/brank-edge-team15
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8050 # The port that the container exposes
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:                    # Environment variables supplied to the Pod
            - name: DEVELOPER_SERVICE_BASEURL
              value: "developer-service-server:8052"
            - name: GAME_SERVICE_BASEURL
              value: "game-service-server:8051"
---
apiVersion: v1                
kind: Service                 
metadata:
  name: brankedge-service-server
  labels:
    app: brankedge-service-server
spec:
  type: NodePort
  selector:
    app: brankedge-service-server
  ports:
    - name: http
      port: 8050
      targetPort: 8050
